language: java

jdk:
  - oraclejdk8

before_cache:
  # Make the cache stable between builds by removing build output
  - rm -rf $HOME/.m2/repository/com/suphawking
cache:
  directories:
    - $HOME/.m2/repository

script:
  - jdk_switcher use oraclejdk8
  - mvn clean package 
  - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
